purge-cmds:
  - 'auxprotect 90d'
  - 'auxprotect_spam 30d'
  - 'auxprotect_inventory 30d'
Actions:
  leash:
    Enabled: true
  session:
    Enabled: true
  kick:
    Enabled: true
  shop:
    Enabled: true
  bucket:
    Enabled: true
  mount:
    Enabled: true
  respawn:
    Enabled: true
  consume:
    Enabled: true
  recover:
    Enabled: true
  money:
    Enabled: true
  pos:
    Enabled: true
  hurt:
    Enabled: true
  inv:
    Enabled: true
  command:
    Enabled: true
  kill:
    Enabled: true
  land:
    Enabled: true
  ip:
    Enabled: true
  username:
    Enabled: true
  inventory:
    Enabled: true
    WorldChange: false
  launch:
    Enabled: true
  grab:
    Enabled: true
  drop:
    Enabled: true
  pickup:
    Enabled: true
  itemframe:
    Enabled: true
  ahlist:
    Enabled: true
  ahbuy:
    Enabled: true