name: AuxProtect
version: 1.1.5
main: dev.heliosares.auxprotect.spigot.AuxProtectSpigot
description: A plugin designed to supplement CoreProtect in a few ways.
api-version: 1.13
softdepend: [ShopGUIPlus, ChestShop, AuctionHouse, Vault, CoreProtect, EconomyShopGUI, EconomyShopGUI-Premium, DynamicShop, Jobs]

commands:
    auxprotect:
        usage: /auxprotect
        description: Base command
        aliases: [ap]
    claiminv:
        usage: /claiminv
        description: Claim a recovered inventory